# Generated by Django 4.0.3 on 2022-03-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_fetcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
