# Generated by Django 4.0.3 on 2022-03-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_fetcher', '0002_inventory_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
